baseURL = "https://spacelavr.github.io/hugo-multilingual/"
copyright = "MIT"

[languages]
[languages.en]
title = "Hugo multilingual site"
weight = 1

[languages.ru]
title = "Hugo многоязычный сайт"
weight = 2
